'use client';

// import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Reemplazo de Geist
import { ConfigProvider } from "antd";
import "./globals.css";
import useAuth from "@/hooks/useAuth";
import { useEffect } from "react";
import { useRouter } from "next/navigation";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const {token} =  useAuth();
  const router = useRouter();

  useEffect( () =>{
    if(!token){
      router.push('/auth/login');
      }
  }, [token, router]);

  return (
    <html lang="es">
      <body className={`${inter.variable} antialiased`}>
        <ConfigProvider wave={{ disabled: true }}>{children}</ConfigProvider>
      </body>
    </html>
  );
}
