import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Reemplazo de Geist
import { ConfigProvider } from "antd";
import './globals.css';

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {


  return (
    <html lang="es">
      <body className={`${inter.variable} antialiased`}>
        <ConfigProvider wave={{ disabled: true }}>{children}</ConfigProvider>
      </body>
    </html>
  );
}
